/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package com.dddzer.repository;

import com.dddzer.domain.Account;
import com.dddzer.repository.support.Repository;

/**
 * The AccountRepository is a data-centric service for the {@link Account} entity.
 * It provides the expected methods to get/delete a {@link Account} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link Account} instance used
 * as a properties holder against which the search will be performed and a {@link SearchParameters}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface AccountRepository extends Repository<Account, Integer> {

    /**
     * Return the persistent instance of {@link Account} with the given unique property value login,
     * or null if there is no such persistent instance.
     *
     * @param login the unique value
     * @return the corresponding {@link Account} persistent instance or null
     */
    Account getByLogin(String login);

    /**
     * Delete a {@link Account} using the unique column login
     *
     * @param login the unique value
     */
    void deleteByLogin(String login);

    /**
     * Return the persistent instance of {@link Account} with the given unique property value password,
     * or null if there is no such persistent instance.
     *
     * @param password the unique value
     * @return the corresponding {@link Account} persistent instance or null
     */
    Account getByPassword(String password);

    /**
     * Delete a {@link Account} using the unique column password
     *
     * @param password the unique value
     */
    void deleteByPassword(String password);
}