/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.dddzer.dao.support.GenericDao;
import com.dddzer.repository.support.RepositoryImpl;
import com.dddzer.domain.Category;
import com.dddzer.dao.CategoryDao;

/**
 * Default implementation of the {@link CategoryRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see CategoryRepository
 */
@Named("categoryRepository")
@Singleton
public class CategoryRepositoryImpl extends RepositoryImpl<Category, Integer> implements CategoryRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(CategoryRepositoryImpl.class);

    protected CategoryDao categoryDao;

    @Inject
    public void setCategoryDao(CategoryDao categoryDao) {
        this.categoryDao = categoryDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Category, Integer> getDao() {
        return categoryDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Category getNew() {
        return new Category();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Category getNewWithDefaults() {
        Category result = getNew();
        result.initDefaultValues();
        return result;
    }

}