/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;
import org.springframework.transaction.annotation.Transactional;

import com.dddzer.dao.support.GenericDao;
import com.dddzer.repository.support.RepositoryImpl;
import com.dddzer.domain.Product;
import com.dddzer.dao.ProductDao;

/**
 * Default implementation of the {@link ProductRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see ProductRepository
 */
@Named("productRepository")
@Singleton
public class ProductRepositoryImpl extends RepositoryImpl<Product, Integer> implements ProductRepository {

    private static final Logger log = Logger.getLogger(ProductRepositoryImpl.class);

    protected ProductDao productDao;

    @Inject
    public void setProductDao(ProductDao productDao) {
        this.productDao = productDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Product, Integer> getDao() {
        return productDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Product getNew() {
        return new Product();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Product getNewWithDefaults() {
        Product result = getNew();
        result.initDefaultValues();
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void delete(Product product) {
        if (product == null) {
            if (log.isDebugEnabled()) {
                log.debug("Skipping deletion for null model!");
            }

            return;
        }

        // remove the reference from the associated part
        if (product.getPart() != null) {
            product.getPart().removeProduct(product);
        }

        super.delete(product);
    }
}