/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.dddzer.dao.support.GenericDao;
import com.dddzer.repository.support.RepositoryImpl;
import com.dddzer.domain.User;
import com.dddzer.dao.UserDao;

/**
 * Default implementation of the {@link UserRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see UserRepository
 */
@Named("userRepository")
@Singleton
public class UserRepositoryImpl extends RepositoryImpl<User, Integer> implements UserRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UserRepositoryImpl.class);

    protected UserDao userDao;

    @Inject
    public void setUserDao(UserDao userDao) {
        this.userDao = userDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<User, Integer> getDao() {
        return userDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User getNew() {
        return new User();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User getNewWithDefaults() {
        User result = getNew();
        result.initDefaultValues();
        return result;
    }

}