/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/printer/Printer.e.vm.java
 */
package com.dddzer.printer;

import static org.apache.commons.lang.StringUtils.isBlank;

import javax.inject.Named;
import javax.inject.Singleton;

import java.util.Locale;

import com.dddzer.domain.FaqAnswer;
import com.dddzer.printer.DiscoverablePrinter;

/**
 * {@link org.springframework.format.Printer} for {@link FaqAnswer} 
 *
 * @see org.springframework.format.Printer
 * @see DiscoverablePrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class FaqAnswerPrinter extends DiscoverablePrinter<FaqAnswer> {
    public FaqAnswerPrinter() {
        super(FaqAnswer.class);
    }

    @Override
    public String print(FaqAnswer faqAnswer, Locale locale) {
        if (faqAnswer == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder(256);
        if (!isBlank(faqAnswer.getQuestion())) {
            if (ret.length() != 0) {
                ret.append('/');
            }
            ret.append(faqAnswer.getQuestion().trim());
        }
        return ret.toString();
    }
}
