/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/printer/Printer.e.vm.java
 */
package com.dddzer.printer;

import static org.apache.commons.lang.StringUtils.isBlank;

import javax.inject.Named;
import javax.inject.Singleton;

import java.util.Locale;

import com.dddzer.domain.Product;
import com.dddzer.printer.DiscoverablePrinter;

/**
 * {@link org.springframework.format.Printer} for {@link Product} 
 *
 * @see org.springframework.format.Printer
 * @see DiscoverablePrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class ProductPrinter extends DiscoverablePrinter<Product> {
    public ProductPrinter() {
        super(Product.class);
    }

    @Override
    public String print(Product product, Locale locale) {
        if (product == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder(256);
        if (!isBlank(product.getProductFileName())) {
            if (ret.length() != 0) {
                ret.append('/');
            }
            ret.append(product.getProductFileName().trim());
        }
        if (!isBlank(product.getProductContentType())) {
            if (ret.length() != 0) {
                ret.append('/');
            }
            ret.append(product.getProductContentType().trim());
        }
        if (!isBlank(product.getDescription_())) {
            if (ret.length() != 0) {
                ret.append('/');
            }
            ret.append(product.getDescription_().trim());
        }
        return ret.toString();
    }
}
