/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package com.dddzer.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.domain.Part;
import com.dddzer.domain.Role;

@StaticMetamodel(Account.class)
public abstract class Account_ {

    // Raw attributes
    public static volatile SingularAttribute<Account, Integer> id;
    public static volatile SingularAttribute<Account, String> login;
    public static volatile SingularAttribute<Account, String> password;
    public static volatile SingularAttribute<Account, String> email;
    public static volatile SingularAttribute<Account, Boolean> isEnabled;

    // One to many
    public static volatile ListAttribute<Account, Part> parts;
    public static volatile ListAttribute<Account, FaqQuestion> faqQuestions;

    // Many to many
    public static volatile ListAttribute<Account, Role> roles;
}