/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.dddzer.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.domain.IdentifiableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "faq_answer")
@FilterDef(name = "myFaqAnswerFilter", defaultCondition = "account_id = :currentAccountId ", parameters = @ParamDef(name = "currentAccountId", type = "org.hibernate.type.IntegerType"))
@Filter(name = "myFaqAnswerFilter")
public class FaqAnswer implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(FaqAnswer.class);

    // Raw attributes
    private Integer id; // pk
    private String question;

    // Technical attributes for query by example
    private Integer faqQuestionId; // not null
    private Integer accountId; // not null

    // Many to one
    private FaqQuestion faqQuestion; // not null (faqQuestionId)
    private Account account; // not null (accountId)

    // ---------------------------
    // Constructors
    // ---------------------------

    public FaqAnswer() {
    }

    public FaqAnswer(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [question] ------------------------

    @Size(max = 200)
    @Column(name = "question", length = 200)
    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    // -- [faqQuestionId] ------------------------

    @Column(name = "faq_question_id", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getFaqQuestionId() {
        return faqQuestionId;
    }

    private void setFaqQuestionId(Integer faqQuestionId) {
        this.faqQuestionId = faqQuestionId;
    }

    // -- [accountId] ------------------------

    @Column(name = "account_id", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getAccountId() {
        return accountId;
    }

    private void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    // --------------------------------------------------------------------
    // Many to One support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FaqAnswer.faqQuestionId ==> FaqQuestion.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "faq_question_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public FaqQuestion getFaqQuestion() {
        return faqQuestion;
    }

    /**
     * Set the faqQuestion without adding this FaqAnswer instance on the passed faqQuestion
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link FaqQuestion}
     */
    public void setFaqQuestion(FaqQuestion faqQuestion) {
        this.faqQuestion = faqQuestion;

        // We set the foreign key property so it can be used by our JPA search by Example facility.
        if (faqQuestion != null) {
            setFaqQuestionId(faqQuestion.getId());
        } else {
            setFaqQuestionId(null);
        }
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FaqAnswer.accountId ==> Account.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "account_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Account getAccount() {
        return account;
    }

    /**
     * Set the account without adding this FaqAnswer instance on the passed account
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Account}
     */
    public void setAccount(Account account) {
        this.account = account;

        // We set the foreign key property so it can be used by our JPA search by Example facility.
        if (account != null) {
            setAccountId(account.getId());
        } else {
            setAccountId(null);
        }
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof FaqAnswer && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this FaqAnswer instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("question", getQuestion()) //
                .add("faqQuestionId", getFaqQuestionId()) //
                .add("accountId", getAccountId()) //
                .toString();
    }
}