/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package com.dddzer.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqQuestion;

@StaticMetamodel(FaqAnswer.class)
public abstract class FaqAnswer_ {

    // Raw attributes
    public static volatile SingularAttribute<FaqAnswer, Integer> id;
    public static volatile SingularAttribute<FaqAnswer, String> question;

    // Technical attributes for query by example
    public static volatile SingularAttribute<FaqAnswer, Integer> faqQuestionId;
    public static volatile SingularAttribute<FaqAnswer, Integer> accountId;

    // Many to one
    public static volatile SingularAttribute<FaqAnswer, FaqQuestion> faqQuestion;
    public static volatile SingularAttribute<FaqAnswer, Account> account;
}