/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.dddzer.domain;

import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqAnswer;
import com.dddzer.domain.IdentifiableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "faq_question")
@FilterDef(name = "myFaqQuestionFilter", defaultCondition = "account_id = :currentAccountId ", parameters = @ParamDef(name = "currentAccountId", type = "org.hibernate.type.IntegerType"))
@Filter(name = "myFaqQuestionFilter")
public class FaqQuestion implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(FaqQuestion.class);

    // Raw attributes
    private Integer id; // pk
    private String anwser;

    // Technical attributes for query by example
    private Integer accountId; // not null

    // Many to one
    private Account account; // not null (accountId)

    // One to many
    private List<FaqAnswer> faqAnswers = new ArrayList<FaqAnswer>();

    // ---------------------------
    // Constructors
    // ---------------------------

    public FaqQuestion() {
    }

    public FaqQuestion(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [anwser] ------------------------

    @Size(max = 200)
    @Column(name = "anwser", length = 200)
    public String getAnwser() {
        return anwser;
    }

    public void setAnwser(String anwser) {
        this.anwser = anwser;
    }

    // -- [accountId] ------------------------

    @Column(name = "account_id", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getAccountId() {
        return accountId;
    }

    private void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    // --------------------------------------------------------------------
    // Many to One support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FaqQuestion.accountId ==> Account.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "account_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Account getAccount() {
        return account;
    }

    /**
     * Set the account without adding this FaqQuestion instance on the passed account
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Account}
     */
    public void setAccount(Account account) {
        this.account = account;

        // We set the foreign key property so it can be used by our JPA search by Example facility.
        if (account != null) {
            setAccountId(account.getId());
        } else {
            setAccountId(null);
        }
    }

    // --------------------------------------------------------------------
    // One to Many support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: faqQuestion ==> faqAnswers
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @OneToMany(mappedBy = "faqQuestion", orphanRemoval = true, cascade = ALL)
    public List<FaqAnswer> getFaqAnswers() {
        return faqAnswers;
    }

    /**
     * Set the {@link FaqAnswer} list.
     * It is recommended to use the helper method {@link #addFaqAnswer(FaqAnswer)} / {@link #removeFaqAnswer(FaqAnswer)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param faqAnswers the list to set
     */
    public void setFaqAnswers(List<FaqAnswer> faqAnswers) {
        this.faqAnswers = faqAnswers;
    }

    /**
     * Helper method to add the passed {@link FaqAnswer} to the faqAnswers list
     * and set this faqQuestion on the passed faqAnswer to preserve referential
     * integrity at the object level.
     *
     * @param faqAnswer the to add
     * @return true if the faqAnswer could be added to the faqAnswers list, false otherwise
     */
    public boolean addFaqAnswer(FaqAnswer faqAnswer) {
        if (getFaqAnswers().add(faqAnswer)) {
            faqAnswer.setFaqQuestion((FaqQuestion) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to remove the passed {@link FaqAnswer} from the faqAnswers list and unset
     * this faqQuestion from the passed faqAnswer to preserve referential integrity at the object level.
     *
     * @param faqAnswer the instance to remove
     * @return true if the faqAnswer could be removed from the faqAnswers list, false otherwise
     */
    public boolean removeFaqAnswer(FaqAnswer faqAnswer) {
        if (getFaqAnswers().remove(faqAnswer)) {
            faqAnswer.setFaqQuestion(null);
            return true;
        }
        return false;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof FaqQuestion && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this FaqQuestion instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("anwser", getAnwser()) //
                .add("accountId", getAccountId()) //
                .toString();
    }
}