/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package com.dddzer.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.dddzer.domain.Account;
import com.dddzer.domain.Category;
import com.dddzer.domain.Product;

@StaticMetamodel(Part.class)
public abstract class Part_ {

    // Raw attributes
    public static volatile SingularAttribute<Part, Integer> id;
    public static volatile SingularAttribute<Part, String> name;
    public static volatile SingularAttribute<Part, String> model;
    public static volatile SingularAttribute<Part, String> serial;
    public static volatile SingularAttribute<Part, String> partCode;
    public static volatile SingularAttribute<Part, String> partName;

    // Technical attributes for query by example
    public static volatile SingularAttribute<Part, Integer> accountId;
    public static volatile SingularAttribute<Part, Integer> categoryId;

    // Many to one
    public static volatile SingularAttribute<Part, Category> category;
    public static volatile SingularAttribute<Part, Account> account;

    // One to many
    public static volatile ListAttribute<Part, Product> products;
}