/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package com.dddzer.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.dddzer.domain.Account;
import com.dddzer.domain.Part;
import com.dddzer.domain.ProductType;

@StaticMetamodel(Product.class)
public abstract class Product_ {

    // Raw attributes
    public static volatile SingularAttribute<Product, Integer> id;
    public static volatile SingularAttribute<Product, Integer> productSize;
    public static volatile SingularAttribute<Product, String> productFileName;
    public static volatile SingularAttribute<Product, String> productContentType;
    public static volatile SingularAttribute<Product, byte[]> productBinary;
    public static volatile SingularAttribute<Product, String> description_;
    public static volatile SingularAttribute<Product, Integer> price;

    // Technical attributes for query by example
    public static volatile SingularAttribute<Product, Integer> productTypeId;
    public static volatile SingularAttribute<Product, Integer> partId;
    public static volatile SingularAttribute<Product, Integer> accoutId;

    // Many to one
    public static volatile SingularAttribute<Product, Part> part;
    public static volatile SingularAttribute<Product, Account> accout;
    public static volatile SingularAttribute<Product, ProductType> productType;
}