/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.dddzer.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.dddzer.domain.Category;
import com.dddzer.repository.CategoryRepositoryImpl;
import com.dddzer.dao.CategoryDao;
import com.dddzer.dao.support.SearchParameters;

/**
 * Unit test on CategoryRepositoryImpl
 */
public class CategoryRepositoryImplTest {

    private CategoryRepositoryImpl categoryRepositoryImpl;
    private CategoryDao categoryDao;

    @Before
    public void setUp() {
        // called before each test.
        categoryRepositoryImpl = new CategoryRepositoryImpl();
        categoryDao = mock(CategoryDao.class);
        categoryRepositoryImpl.setCategoryDao(categoryDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Category none = null;

        when(categoryDao.findUniqueOrNone(any(Category.class), any(SearchParameters.class))).thenReturn(none);

        Category result = categoryRepositoryImpl.findUniqueOrNone(new Category());

        assertThat(result).isNull();
        verify(categoryDao, times(1)).findUniqueOrNone(any(Category.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Category unique = new Category();

        when(categoryDao.findUniqueOrNone(any(Category.class), any(SearchParameters.class))).thenReturn(unique);

        Category result = categoryRepositoryImpl.findUniqueOrNone(new Category());

        assertThat(result).isNotNull();
        verify(categoryDao, times(1)).findUniqueOrNone(any(Category.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(categoryDao.findUniqueOrNone(any(Category.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        categoryRepositoryImpl.findUniqueOrNone(new Category());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(categoryDao.findUnique(any(Category.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        categoryRepositoryImpl.findUnique(new Category());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Category unique = new Category();

        when(categoryDao.findUnique(any(Category.class), any(SearchParameters.class))).thenReturn(unique);

        Category result = categoryRepositoryImpl.findUnique(new Category());

        assertThat(result).isNotNull();
        verify(categoryDao, times(1)).findUnique(any(Category.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(categoryDao.findUnique(any(Category.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        categoryRepositoryImpl.findUnique(new Category());
    }
}