/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqAnswer;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.repository.AccountGenerator;
import com.dddzer.repository.AccountRepository;
import com.dddzer.repository.FaqQuestionGenerator;
import com.dddzer.repository.FaqQuestionRepository;
import com.dddzer.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class FaqAnswerGenerator {

    /**
     * Returns a new FaqAnswer instance filled with random values.
     */
    public FaqAnswer getFaqAnswer() {
        FaqAnswer faqAnswer = new FaqAnswer();

        // simple attributes follows
        faqAnswer.setQuestion("a");
        // mandatory relation
        FaqQuestion faqQuestion = faqQuestionGenerator.getFaqQuestion();
        faqQuestionRepository.save(faqQuestion);
        faqAnswer.setFaqQuestion(faqQuestion);
        // mandatory relation
        Account account = accountGenerator.getAccount();
        accountRepository.save(account);
        faqAnswer.setAccount(account);
        return faqAnswer;
    }

    @Inject
    private FaqQuestionRepository faqQuestionRepository;
    @Inject
    private FaqQuestionGenerator faqQuestionGenerator;
    @Inject
    private AccountRepository accountRepository;
    @Inject
    private AccountGenerator accountGenerator;
}