/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.repository.AccountGenerator;
import com.dddzer.repository.AccountRepository;
import com.dddzer.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class FaqQuestionGenerator {

    /**
     * Returns a new FaqQuestion instance filled with random values.
     */
    public FaqQuestion getFaqQuestion() {
        FaqQuestion faqQuestion = new FaqQuestion();

        // simple attributes follows
        faqQuestion.setAnwser("a");
        // mandatory relation
        Account account = accountGenerator.getAccount();
        accountRepository.save(account);
        faqQuestion.setAccount(account);
        return faqQuestion;
    }

    @Inject
    private AccountRepository accountRepository;
    @Inject
    private AccountGenerator accountGenerator;
}