/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.dddzer.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.dddzer.domain.Part;
import com.dddzer.repository.PartRepositoryImpl;
import com.dddzer.dao.PartDao;
import com.dddzer.dao.support.SearchParameters;

/**
 * Unit test on PartRepositoryImpl
 */
public class PartRepositoryImplTest {

    private PartRepositoryImpl partRepositoryImpl;
    private PartDao partDao;

    @Before
    public void setUp() {
        // called before each test.
        partRepositoryImpl = new PartRepositoryImpl();
        partDao = mock(PartDao.class);
        partRepositoryImpl.setPartDao(partDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Part none = null;

        when(partDao.findUniqueOrNone(any(Part.class), any(SearchParameters.class))).thenReturn(none);

        Part result = partRepositoryImpl.findUniqueOrNone(new Part());

        assertThat(result).isNull();
        verify(partDao, times(1)).findUniqueOrNone(any(Part.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Part unique = new Part();

        when(partDao.findUniqueOrNone(any(Part.class), any(SearchParameters.class))).thenReturn(unique);

        Part result = partRepositoryImpl.findUniqueOrNone(new Part());

        assertThat(result).isNotNull();
        verify(partDao, times(1)).findUniqueOrNone(any(Part.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(partDao.findUniqueOrNone(any(Part.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        partRepositoryImpl.findUniqueOrNone(new Part());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(partDao.findUnique(any(Part.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        partRepositoryImpl.findUnique(new Part());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Part unique = new Part();

        when(partDao.findUnique(any(Part.class), any(SearchParameters.class))).thenReturn(unique);

        Part result = partRepositoryImpl.findUnique(new Part());

        assertThat(result).isNotNull();
        verify(partDao, times(1)).findUnique(any(Part.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(partDao.findUnique(any(Part.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        partRepositoryImpl.findUnique(new Part());
    }
}