/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.dddzer.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.dddzer.domain.Product;
import com.dddzer.repository.ProductRepositoryImpl;
import com.dddzer.dao.ProductDao;
import com.dddzer.dao.support.SearchParameters;

/**
 * Unit test on ProductRepositoryImpl
 */
public class ProductRepositoryImplTest {

    private ProductRepositoryImpl productRepositoryImpl;
    private ProductDao productDao;

    @Before
    public void setUp() {
        // called before each test.
        productRepositoryImpl = new ProductRepositoryImpl();
        productDao = mock(ProductDao.class);
        productRepositoryImpl.setProductDao(productDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Product none = null;

        when(productDao.findUniqueOrNone(any(Product.class), any(SearchParameters.class))).thenReturn(none);

        Product result = productRepositoryImpl.findUniqueOrNone(new Product());

        assertThat(result).isNull();
        verify(productDao, times(1)).findUniqueOrNone(any(Product.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Product unique = new Product();

        when(productDao.findUniqueOrNone(any(Product.class), any(SearchParameters.class))).thenReturn(unique);

        Product result = productRepositoryImpl.findUniqueOrNone(new Product());

        assertThat(result).isNotNull();
        verify(productDao, times(1)).findUniqueOrNone(any(Product.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(productDao.findUniqueOrNone(any(Product.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        productRepositoryImpl.findUniqueOrNone(new Product());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(productDao.findUnique(any(Product.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        productRepositoryImpl.findUnique(new Product());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Product unique = new Product();

        when(productDao.findUnique(any(Product.class), any(SearchParameters.class))).thenReturn(unique);

        Product result = productRepositoryImpl.findUnique(new Product());

        assertThat(result).isNotNull();
        verify(productDao, times(1)).findUnique(any(Product.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(productDao.findUnique(any(Product.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        productRepositoryImpl.findUnique(new Product());
    }
}