/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.dddzer.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.dddzer.domain.ProductType;
import com.dddzer.repository.ProductTypeRepositoryImpl;
import com.dddzer.dao.ProductTypeDao;
import com.dddzer.dao.support.SearchParameters;

/**
 * Unit test on ProductTypeRepositoryImpl
 */
public class ProductTypeRepositoryImplTest {

    private ProductTypeRepositoryImpl productTypeRepositoryImpl;
    private ProductTypeDao productTypeDao;

    @Before
    public void setUp() {
        // called before each test.
        productTypeRepositoryImpl = new ProductTypeRepositoryImpl();
        productTypeDao = mock(ProductTypeDao.class);
        productTypeRepositoryImpl.setProductTypeDao(productTypeDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        ProductType none = null;

        when(productTypeDao.findUniqueOrNone(any(ProductType.class), any(SearchParameters.class))).thenReturn(none);

        ProductType result = productTypeRepositoryImpl.findUniqueOrNone(new ProductType());

        assertThat(result).isNull();
        verify(productTypeDao, times(1)).findUniqueOrNone(any(ProductType.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        ProductType unique = new ProductType();

        when(productTypeDao.findUniqueOrNone(any(ProductType.class), any(SearchParameters.class))).thenReturn(unique);

        ProductType result = productTypeRepositoryImpl.findUniqueOrNone(new ProductType());

        assertThat(result).isNotNull();
        verify(productTypeDao, times(1)).findUniqueOrNone(any(ProductType.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(productTypeDao.findUniqueOrNone(any(ProductType.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        productTypeRepositoryImpl.findUniqueOrNone(new ProductType());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(productTypeDao.findUnique(any(ProductType.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        productTypeRepositoryImpl.findUnique(new ProductType());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        ProductType unique = new ProductType();

        when(productTypeDao.findUnique(any(ProductType.class), any(SearchParameters.class))).thenReturn(unique);

        ProductType result = productTypeRepositoryImpl.findUnique(new ProductType());

        assertThat(result).isNotNull();
        verify(productTypeDao, times(1)).findUnique(any(ProductType.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(productTypeDao.findUnique(any(ProductType.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        productTypeRepositoryImpl.findUnique(new ProductType());
    }
}