/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.dddzer.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.dddzer.domain.Part;
import com.dddzer.domain.Product;
import com.dddzer.domain.ProductType;
import com.dddzer.repository.PartGenerator;
import com.dddzer.repository.PartRepository;
import com.dddzer.repository.ProductTypeGenerator;
import com.dddzer.repository.ProductTypeRepository;
import com.dddzer.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class ProductGenerator {

    /**
     * Returns a new Product instance filled with random values.
     */
    public Product getProduct() {
        Product product = new Product();

        // simple attributes follows
        product.setProductSize(1);
        product.setProductFileName("a");
        product.setProductContentType("a");
        product.setProductBinary("d".getBytes());
        product.setDescription_("a");
        product.setPrice(1);
        // mandatory relation
        Part part = partGenerator.getPart();
        partRepository.save(part);
        product.setPart(part);
        // mandatory relation
        ProductType productType = productTypeGenerator.getProductType();
        productTypeRepository.save(productType);
        product.setProductType(productType);
        return product;
    }

    @Inject
    private PartRepository partRepository;
    @Inject
    private PartGenerator partGenerator;
    @Inject
    private ProductTypeRepository productTypeRepository;
    @Inject
    private ProductTypeGenerator productTypeGenerator;
}