/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.dddzer.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.dddzer.domain.User;
import com.dddzer.repository.UserRepositoryImpl;
import com.dddzer.dao.UserDao;
import com.dddzer.dao.support.SearchParameters;

/**
 * Unit test on UserRepositoryImpl
 */
public class UserRepositoryImplTest {

    private UserRepositoryImpl userRepositoryImpl;
    private UserDao userDao;

    @Before
    public void setUp() {
        // called before each test.
        userRepositoryImpl = new UserRepositoryImpl();
        userDao = mock(UserDao.class);
        userRepositoryImpl.setUserDao(userDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        User none = null;

        when(userDao.findUniqueOrNone(any(User.class), any(SearchParameters.class))).thenReturn(none);

        User result = userRepositoryImpl.findUniqueOrNone(new User());

        assertThat(result).isNull();
        verify(userDao, times(1)).findUniqueOrNone(any(User.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        User unique = new User();

        when(userDao.findUniqueOrNone(any(User.class), any(SearchParameters.class))).thenReturn(unique);

        User result = userRepositoryImpl.findUniqueOrNone(new User());

        assertThat(result).isNotNull();
        verify(userDao, times(1)).findUniqueOrNone(any(User.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(userDao.findUniqueOrNone(any(User.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        userRepositoryImpl.findUniqueOrNone(new User());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(userDao.findUnique(any(User.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        userRepositoryImpl.findUnique(new User());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        User unique = new User();

        when(userDao.findUnique(any(User.class), any(SearchParameters.class))).thenReturn(unique);

        User result = userRepositoryImpl.findUnique(new User());

        assertThat(result).isNotNull();
        verify(userDao, times(1)).findUnique(any(User.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(userDao.findUnique(any(User.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        userRepositoryImpl.findUnique(new User());
    }
}