/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.dddzer.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.dddzer.util.*;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqQuestion;

/**
 * Basic tests for FaqAnswer
 */
@SuppressWarnings("unused")
public class FaqAnswerTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        FaqAnswer model = new FaqAnswer();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        FaqAnswer model = new FaqAnswer();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  FaqAnswer.faqQuestionId ==> FaqQuestion.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setFaqQuestion() {
        FaqAnswer many = new FaqAnswer();

        // init
        FaqQuestion one = new FaqQuestion();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setFaqQuestion(one);

        // make sure it is propagated properly
        assertNotNull(many.getFaqQuestionId());
        assertEquals(one, many.getFaqQuestion());
        assertSame(many.getFaqQuestionId(), one.getId());
        // now set it to back to null
        many.setFaqQuestion(null);

        // make sure null is propagated properly
        assertNull(many.getFaqQuestion());

        // make sure it is propagated on fk column as well
        assertNull(many.getFaqQuestionId());
    }

    @Test
    public void manyToOne_setAccount() {
        FaqAnswer many = new FaqAnswer();

        // init
        Account one = new Account();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    @Test
    public void toStringNotNull() {
        FaqAnswer model = new FaqAnswer();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        FaqAnswer model1 = new FaqAnswer();
        FaqAnswer model2 = new FaqAnswer();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setQuestion("a");
        model2.setQuestion("a");
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}