/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.dddzer.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.dddzer.util.*;
import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqAnswer;

/**
 * Basic tests for FaqQuestion
 */
@SuppressWarnings("unused")
public class FaqQuestionTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        FaqQuestion model = new FaqQuestion();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        FaqQuestion model = new FaqQuestion();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  FaqQuestion.accountId ==> Account.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setAccount() {
        FaqQuestion many = new FaqQuestion();

        // init
        Account one = new Account();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    //-------------------------------------------------------------
    // One to Many: SimpleOneToMany faq_question.id ==> faq_answer.faq_question_id
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // faqAnswer.faqAnswer <-- faqQuestion.faqQuestions
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addFaqAnswer() {
        FaqQuestion one = new FaqQuestion();
        FaqAnswer many = new FaqAnswer();

        // init
        one.addFaqAnswer(many);

        // make sure it is propagated
        assertTrue(one.getFaqAnswers().contains(many));
        assertTrue(one.equals(many.getFaqQuestion()));

        // now set it to null
        one.removeFaqAnswer(many);

        // make sure null is propagated
        assertFalse(one.getFaqAnswers().contains(many));
        assertNull(many.getFaqQuestion());
    }

    @Test
    public void toStringNotNull() {
        FaqQuestion model = new FaqQuestion();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        FaqQuestion model1 = new FaqQuestion();
        FaqQuestion model2 = new FaqQuestion();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setAnwser("a");
        model2.setAnwser("a");
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}