/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.dddzer.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.dddzer.util.*;
import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.Category;
import com.dddzer.domain.Product;

/**
 * Basic tests for Part
 */
@SuppressWarnings("unused")
public class PartTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Part model = new Part();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        Part model = new Part();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Part.categoryId ==> Category.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setCategory() {
        Part many = new Part();

        // init
        Category one = new Category();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setCategory(one);

        // make sure it is propagated properly
        assertNotNull(many.getCategoryId());
        assertEquals(one, many.getCategory());
        assertSame(many.getCategoryId(), one.getId());
        // now set it to back to null
        many.setCategory(null);

        // make sure null is propagated properly
        assertNull(many.getCategory());

        // make sure it is propagated on fk column as well
        assertNull(many.getCategoryId());
    }

    @Test
    public void manyToOne_setAccount() {
        Part many = new Part();

        // init
        Account one = new Account();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    //-------------------------------------------------------------
    // One to Many: SimpleOneToMany part.id ==> product.part_id
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // product.product <-- part.parts
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addProduct() {
        Part one = new Part();
        Product many = new Product();

        // init
        one.addProduct(many);

        // make sure it is propagated
        assertTrue(one.getProducts().contains(many));
        assertTrue(one.equals(many.getPart()));

        // now set it to null
        one.removeProduct(many);

        // make sure null is propagated
        assertFalse(one.getProducts().contains(many));
        assertNull(many.getPart());
    }

    @Test
    public void toStringNotNull() {
        Part model = new Part();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Part model1 = new Part();
        Part model2 = new Part();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setName("a");
        model2.setName("a");

        model1.setModel("a");
        model2.setModel("a");

        model1.setSerial("a");
        model2.setSerial("a");

        model1.setPartCode("a");
        model2.setPartCode("a");

        model1.setPartName("a");
        model2.setPartName("a");
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}