/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.dddzer.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.dddzer.util.*;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.commons.io.FileUtils;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import com.dddzer.domain.Account;
import com.dddzer.domain.Part;
import com.dddzer.domain.ProductType;

/**
 * Basic tests for Product
 */
@SuppressWarnings("unused")
public class ProductTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Product model = new Product();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        Product model = new Product();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Product.partId ==> Part.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setPart() {
        Product many = new Product();

        // init
        Part one = new Part();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setPart(one);

        // make sure it is propagated properly
        assertNotNull(many.getPartId());
        assertEquals(one, many.getPart());
        assertSame(many.getPartId(), one.getId());
        // now set it to back to null
        many.setPart(null);

        // make sure null is propagated properly
        assertNull(many.getPart());

        // make sure it is propagated on fk column as well
        assertNull(many.getPartId());
    }

    @Test
    public void manyToOne_setAccout() {
        Product many = new Product();

        // init
        Account one = new Account();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setAccout(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccoutId());
        assertEquals(one, many.getAccout());
        assertSame(many.getAccoutId(), one.getId());
        // now set it to back to null
        many.setAccout(null);

        // make sure null is propagated properly
        assertNull(many.getAccout());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccoutId());
    }

    @Test
    public void manyToOne_setProductType() {
        Product many = new Product();

        // init
        ProductType one = new ProductType();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setProductType(one);

        // make sure it is propagated properly
        assertNotNull(many.getProductTypeId());
        assertEquals(one, many.getProductType());
        assertSame(many.getProductTypeId(), one.getId());
        // now set it to back to null
        many.setProductType(null);

        // make sure null is propagated properly
        assertNull(many.getProductType());

        // make sure it is propagated on fk column as well
        assertNull(many.getProductTypeId());
    }

    @Test
    public void toStringNotNull() {
        Product model = new Product();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Product model1 = new Product();
        Product model2 = new Product();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setProductSize(1);
        model2.setProductSize(1);

        model1.setProductFileName("a");
        model2.setProductFileName("a");

        model1.setProductContentType("a");
        model2.setProductContentType("a");

        model1.setProductBinary("d".getBytes());
        model2.setProductBinary("d".getBytes());

        model1.setDescription_("a");
        model2.setDescription_("a");

        model1.setPrice(1);
        model2.setPrice(1);
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}