/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.dao.support.PropertySelector.newPropertySelector;
import static com.dddzer.domain.Account_.isEnabled;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.dao.support.PropertySelector;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.Account;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * View Helper to find/select {@link Account}.
 * It exposes a {@link Account} instance so it can be used in search by Example query.
 */
@Named
@Scope("conversation")
public class AccountSearchForm extends GenericSearchForm<Account, AccountSearchForm> {
    private static final long serialVersionUID = 1L;

    private Account account = new Account();
    private PropertySelector<Account, Boolean> isEnabledSelector = newPropertySelector(isEnabled);

    public Account getAccount() {
        return account;
    }

    @Override
    protected Account getEntity() {
        return account;
    }

    // Selectors for property
    public PropertySelector<Account, Boolean> getIsEnabledSelector() {
        return isEnabledSelector;
    }

    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .propertySelector(isEnabledSelector) //
        ;
    }

    @Override
    public AccountSearchForm newInstance() {
        return new AccountSearchForm();
    }

    @Override
    public void resetWithOther(AccountSearchForm other) {
        this.account = other.getAccount();
        this.isEnabledSelector = other.getIsEnabledSelector();
    }
}