/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.dddzer.web.domain;

import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.Category;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * View Helper to find/select {@link Category}.
 * It exposes a {@link Category} instance so it can be used in search by Example query.
 */
@Named
@Scope("conversation")
public class CategorySearchForm extends GenericSearchForm<Category, CategorySearchForm> {
    private static final long serialVersionUID = 1L;

    private Category category = new Category();

    public Category getCategory() {
        return category;
    }

    @Override
    protected Category getEntity() {
        return category;
    }

    public SearchParameters toSearchParameters() {
        return new SearchParameters().anywhere();
    }

    @Override
    public CategorySearchForm newInstance() {
        return new CategorySearchForm();
    }

    @Override
    public void resetWithOther(CategorySearchForm other) {
        this.category = other.getCategory();
    }
}