/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.Category;
import com.dddzer.repository.CategoryRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.CategoryJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class CategoryLazyDataModel extends GenericLazyDataModel<Category, Integer, CategorySearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private CategoryRepository categoryRepository;
    @Inject
    transient private CategoryJsfConverter categoryConverter;
    @Inject
    transient private CategorySearchForm categorySearchForm;

    private Category[] selectedRows;

    @Override
    protected Repository<Category, Integer> getRepository() {
        return categoryRepository;
    }

    @Override
    protected Converter getConverter() {
        return categoryConverter;
    }

    @Override
    protected GenericSearchForm<Category, CategorySearchForm> getSearchForm() {
        return categorySearchForm;
    }

    @Override
    protected ConversationContext<Category> getSelectedContext(Category selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return CategoryController.newEditContext(selected.getId());
        } else {
            return CategoryController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(Category[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public Category[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<Category>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}