/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.dddzer.web.domain;

import java.util.List;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.servlet.http.HttpServletRequest;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.FaqAnswer;
import com.dddzer.repository.FaqAnswerRepository;
import com.dddzer.web.conversation.Conversation;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.conversation.ConversationFactory;

/**
 * Stateless controller for FaqAnswer conversation start. Provides also auto-complete support. 
 */
@Named
@Singleton
public class FaqAnswerController implements ConversationFactory {
    public final static String editUri = "/domain/faqAnswerEdit.faces";
    public final static String selectUri = "/domain/faqAnswerSelect.faces";
    private FaqAnswerRepository faqAnswerRepository;

    @Inject
    public void setFaqAnswerRepository(FaqAnswerRepository faqAnswerRepository) {
        this.faqAnswerRepository = faqAnswerRepository;
    }

    // --------------------------------
    // ConversationFactoryImpl
    // --------------------------------

    @Override
    public boolean canCreateConversation(HttpServletRequest request) {
        return selectUri.equals(request.getServletPath());
    }

    @Override
    public Conversation createConversation(HttpServletRequest request) {
        String uri = request.getServletPath();
        if (selectUri.equals(uri)) {
            Conversation conversation = Conversation.newInstance(request);
            ConversationContext<FaqAnswer> ctx = newSearchContext();
            ctx.setLabelWithKey("faqAnswer");
            conversation.setNextContext(ctx);
            return conversation;
        }

        throw new IllegalStateException("Unexpected conversation creation demand");
    }

    // --------------------------------
    // Autocomplete support
    // --------------------------------

    /**
     * This method is used from primefaces autocomplete components.
     */
    public List<FaqAnswer> complete(String value) {
        SearchParameters sp = new SearchParameters().anywhere().searchPattern(value);
        return faqAnswerRepository.find(sp);
    }

    // --------------------------------
    // Helper 
    // --------------------------------    

    /**
     * Helper to construct a new ConversationContext to edit an FaqAnswer.
     * @param faqAnswer the entity to edit.
     */
    public static ConversationContext<FaqAnswer> newEditContext(final FaqAnswer faqAnswer) {
        ConversationContext<FaqAnswer> ctx = new ConversationContext<FaqAnswer>();
        ctx.setEntity(faqAnswer); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:faqQuestion");
        ctx.addSourceIgnoringUseConversationEntityManager("form:account");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext to edit an FaqAnswer.
     * @param id the id of the entity to edit.
     */
    public static ConversationContext<FaqAnswer> newEditContext(final Integer id) {
        ConversationContext<FaqAnswer> ctx = new ConversationContext<FaqAnswer>();
        ctx.setEntityId(id); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:faqQuestion");
        ctx.addSourceIgnoringUseConversationEntityManager("form:account");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext for search/selection.
     */
    public static ConversationContext<FaqAnswer> newSearchContext() {
        ConversationContext<FaqAnswer> ctx = new ConversationContext<FaqAnswer>();
        ctx.setUseConversationEntityManager(false);
        ctx.setViewUri(selectUri);
        return ctx;
    }
}