/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.dao.support.EntitySelector.newEntitySelector;
import static com.dddzer.domain.FaqAnswer_.accountId;
import static com.dddzer.domain.FaqAnswer_.faqQuestion;
import static com.dddzer.domain.FaqAnswer_.faqQuestionId;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.dao.support.EntitySelector;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.Account;
import com.dddzer.domain.FaqAnswer;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * View Helper to find/select {@link FaqAnswer}.
 * It exposes a {@link FaqAnswer} instance so it can be used in search by Example query.
 */
@Named
@Scope("conversation")
public class FaqAnswerSearchForm extends GenericSearchForm<FaqAnswer, FaqAnswerSearchForm> {
    private static final long serialVersionUID = 1L;

    private FaqAnswer faqAnswer = new FaqAnswer();
    private EntitySelector<FaqAnswer, FaqQuestion, Integer> faqQuestionSelector = newEntitySelector(faqQuestionId);
    private EntitySelector<FaqAnswer, Account, Integer> accountSelector = newEntitySelector(accountId);

    public FaqAnswer getFaqAnswer() {
        return faqAnswer;
    }

    @Override
    protected FaqAnswer getEntity() {
        return faqAnswer;
    }

    // Selectors for x-to-one associations
    public EntitySelector<FaqAnswer, FaqQuestion, Integer> getFaqQuestionSelector() {
        return faqQuestionSelector;
    }

    public EntitySelector<FaqAnswer, Account, Integer> getAccountSelector() {
        return accountSelector;
    }

    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .leftJoin(faqQuestion) //
                .entitySelector(faqQuestionSelector) //
                .entitySelector(accountSelector) //
        ;
    }

    @Override
    public FaqAnswerSearchForm newInstance() {
        return new FaqAnswerSearchForm();
    }

    @Override
    public void resetWithOther(FaqAnswerSearchForm other) {
        this.faqAnswer = other.getFaqAnswer();
        this.faqQuestionSelector = other.getFaqQuestionSelector();
        this.accountSelector = other.getAccountSelector();
    }
}