/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.FaqAnswer;
import com.dddzer.repository.FaqAnswerRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.FaqAnswerJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class FaqAnswerLazyDataModel extends GenericLazyDataModel<FaqAnswer, Integer, FaqAnswerSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private FaqAnswerRepository faqAnswerRepository;
    @Inject
    transient private FaqAnswerJsfConverter faqAnswerConverter;
    @Inject
    transient private FaqAnswerSearchForm faqAnswerSearchForm;

    private FaqAnswer[] selectedRows;

    @Override
    protected Repository<FaqAnswer, Integer> getRepository() {
        return faqAnswerRepository;
    }

    @Override
    protected Converter getConverter() {
        return faqAnswerConverter;
    }

    @Override
    protected GenericSearchForm<FaqAnswer, FaqAnswerSearchForm> getSearchForm() {
        return faqAnswerSearchForm;
    }

    @Override
    protected ConversationContext<FaqAnswer> getSelectedContext(FaqAnswer selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return FaqAnswerController.newEditContext(selected.getId());
        } else {
            return FaqAnswerController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(FaqAnswer[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public FaqAnswer[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<FaqAnswer>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}