/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.FaqQuestion;
import com.dddzer.repository.FaqQuestionRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.FaqQuestionJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class FaqQuestionLazyDataModel extends GenericLazyDataModel<FaqQuestion, Integer, FaqQuestionSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private FaqQuestionRepository faqQuestionRepository;
    @Inject
    transient private FaqQuestionJsfConverter faqQuestionConverter;
    @Inject
    transient private FaqQuestionSearchForm faqQuestionSearchForm;

    private FaqQuestion[] selectedRows;

    @Override
    protected Repository<FaqQuestion, Integer> getRepository() {
        return faqQuestionRepository;
    }

    @Override
    protected Converter getConverter() {
        return faqQuestionConverter;
    }

    @Override
    protected GenericSearchForm<FaqQuestion, FaqQuestionSearchForm> getSearchForm() {
        return faqQuestionSearchForm;
    }

    @Override
    protected ConversationContext<FaqQuestion> getSelectedContext(FaqQuestion selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return FaqQuestionController.newEditContext(selected.getId());
        } else {
            return FaqQuestionController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(FaqQuestion[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public FaqQuestion[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<FaqQuestion>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}