/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.Part;
import com.dddzer.repository.PartRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.PartJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class PartLazyDataModel extends GenericLazyDataModel<Part, Integer, PartSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private PartRepository partRepository;
    @Inject
    transient private PartJsfConverter partConverter;
    @Inject
    transient private PartSearchForm partSearchForm;

    private Part[] selectedRows;

    @Override
    protected Repository<Part, Integer> getRepository() {
        return partRepository;
    }

    @Override
    protected Converter getConverter() {
        return partConverter;
    }

    @Override
    protected GenericSearchForm<Part, PartSearchForm> getSearchForm() {
        return partSearchForm;
    }

    @Override
    protected ConversationContext<Part> getSelectedContext(Part selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return PartController.newEditContext(selected.getId());
        } else {
            return PartController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(Part[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public Part[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<Part>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}