/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/UploadHandler.e.vm.java
 */
package com.dddzer.web.domain;

import static org.apache.commons.codec.binary.StringUtils.newStringUtf8;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import com.dddzer.domain.Product;

public class ProductUploadHandler {
    private Product product;

    public ProductUploadHandler(Product product) {
        this.product = product;
    }

    /**
     * Primefaces support for productBinary file upload
     */
    public void handleFileUpload(FileUploadEvent fileUploadEvent) {
        UploadedFile uploadedFile = fileUploadEvent.getFile(); //application code
        product.setProductBinary(uploadedFile.getContents());
        product.setProductSize(product.getProductBinary().length);
        product.setProductContentType(uploadedFile.getContentType());
        String filename = FilenameUtils.getName(uploadedFile.getFileName());
        product.setProductFileName(newStringUtf8(filename.getBytes())); //until primefaces bug #3002 is resolved
    }
}