/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.dddzer.web.domain;

import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.ProductType;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * View Helper to find/select {@link ProductType}.
 * It exposes a {@link ProductType} instance so it can be used in search by Example query.
 */
@Named
@Scope("conversation")
public class ProductTypeSearchForm extends GenericSearchForm<ProductType, ProductTypeSearchForm> {
    private static final long serialVersionUID = 1L;

    private ProductType productType = new ProductType();

    public ProductType getProductType() {
        return productType;
    }

    @Override
    protected ProductType getEntity() {
        return productType;
    }

    public SearchParameters toSearchParameters() {
        return new SearchParameters().anywhere();
    }

    @Override
    public ProductTypeSearchForm newInstance() {
        return new ProductTypeSearchForm();
    }

    @Override
    public void resetWithOther(ProductTypeSearchForm other) {
        this.productType = other.getProductType();
    }
}