/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.dddzer.web.domain;

import java.io.ByteArrayInputStream;
import java.util.List;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.servlet.http.HttpServletRequest;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.Product;
import com.dddzer.repository.ProductRepository;
import com.dddzer.web.conversation.Conversation;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.conversation.ConversationFactory;

/**
 * Stateless controller for Product conversation start. Provides also auto-complete support. 
 */
@Named
@Singleton
public class ProductController implements ConversationFactory {
    public final static String editUri = "/domain/productEdit.faces";
    public final static String selectUri = "/domain/productSelect.faces";
    private ProductRepository productRepository;

    @Inject
    public void setProductRepository(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    // --------------------------------
    // ConversationFactoryImpl
    // --------------------------------

    @Override
    public boolean canCreateConversation(HttpServletRequest request) {
        return selectUri.equals(request.getServletPath());
    }

    @Override
    public Conversation createConversation(HttpServletRequest request) {
        String uri = request.getServletPath();
        if (selectUri.equals(uri)) {
            Conversation conversation = Conversation.newInstance(request);
            ConversationContext<Product> ctx = newSearchContext();
            ctx.setLabelWithKey("product");
            conversation.setNextContext(ctx);
            return conversation;
        }

        throw new IllegalStateException("Unexpected conversation creation demand");
    }

    // --------------------------------
    // Autocomplete support
    // --------------------------------

    /**
     * This method is used from primefaces autocomplete components.
     */
    public List<Product> complete(String value) {
        SearchParameters sp = new SearchParameters().anywhere().searchPattern(value);
        return productRepository.find(sp);
    }

    // --------------------------------
    // Upload/Download support 
    // --------------------------------    

    public ProductUploadHandler getUploadHandler(Product product) {
        return new ProductUploadHandler(product);
    }

    /**
     * Primefaces support for productBinary file download
     */
    public StreamedContent getStreamedContent(Product product) {
        return new DefaultStreamedContent(new ByteArrayInputStream(product.getProductBinary()), product.getProductContentType(), product.getProductFileName());
    }

    // --------------------------------
    // Helper 
    // --------------------------------    

    /**
     * Helper to construct a new ConversationContext to edit an Product.
     * @param product the entity to edit.
     */
    public static ConversationContext<Product> newEditContext(final Product product) {
        ConversationContext<Product> ctx = new ConversationContext<Product>();
        ctx.setEntity(product); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:part");
        ctx.addSourceIgnoringUseConversationEntityManager("form:accout");
        ctx.addSourceIgnoringUseConversationEntityManager("form:productType");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext to edit an Product.
     * @param id the id of the entity to edit.
     */
    public static ConversationContext<Product> newEditContext(final Integer id) {
        ConversationContext<Product> ctx = new ConversationContext<Product>();
        ctx.setEntityId(id); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:part");
        ctx.addSourceIgnoringUseConversationEntityManager("form:accout");
        ctx.addSourceIgnoringUseConversationEntityManager("form:productType");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext for search/selection.
     */
    public static ConversationContext<Product> newSearchContext() {
        ConversationContext<Product> ctx = new ConversationContext<Product>();
        ctx.setUseConversationEntityManager(false);
        ctx.setViewUri(selectUri);
        return ctx;
    }
}