/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.dddzer.web.domain;

import java.util.List;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.servlet.http.HttpServletRequest;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.ProductType;
import com.dddzer.repository.ProductTypeRepository;
import com.dddzer.web.conversation.Conversation;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.conversation.ConversationFactory;

/**
 * Stateless controller for ProductType conversation start. Provides also auto-complete support. 
 */
@Named
@Singleton
public class ProductTypeController implements ConversationFactory {
    public final static String editUri = "/domain/productTypeEdit.faces";
    public final static String selectUri = "/domain/productTypeSelect.faces";
    private ProductTypeRepository productTypeRepository;

    @Inject
    public void setProductTypeRepository(ProductTypeRepository productTypeRepository) {
        this.productTypeRepository = productTypeRepository;
    }

    // --------------------------------
    // ConversationFactoryImpl
    // --------------------------------

    @Override
    public boolean canCreateConversation(HttpServletRequest request) {
        return selectUri.equals(request.getServletPath());
    }

    @Override
    public Conversation createConversation(HttpServletRequest request) {
        String uri = request.getServletPath();
        if (selectUri.equals(uri)) {
            Conversation conversation = Conversation.newInstance(request);
            ConversationContext<ProductType> ctx = newSearchContext();
            ctx.setLabelWithKey("productType");
            conversation.setNextContext(ctx);
            return conversation;
        }

        throw new IllegalStateException("Unexpected conversation creation demand");
    }

    // --------------------------------
    // Autocomplete support
    // --------------------------------

    /**
     * This method is used from primefaces autocomplete components.
     */
    public List<ProductType> complete(String value) {
        SearchParameters sp = new SearchParameters().anywhere().searchPattern(value);
        return productTypeRepository.find(sp);
    }

    // --------------------------------
    // Helper 
    // --------------------------------    

    /**
     * Helper to construct a new ConversationContext to edit an ProductType.
     * @param productType the entity to edit.
     */
    public static ConversationContext<ProductType> newEditContext(final ProductType productType) {
        ConversationContext<ProductType> ctx = new ConversationContext<ProductType>();
        ctx.setEntity(productType); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext to edit an ProductType.
     * @param id the id of the entity to edit.
     */
    public static ConversationContext<ProductType> newEditContext(final Integer id) {
        ConversationContext<ProductType> ctx = new ConversationContext<ProductType>();
        ctx.setEntityId(id); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext for search/selection.
     */
    public static ConversationContext<ProductType> newSearchContext() {
        ConversationContext<ProductType> ctx = new ConversationContext<ProductType>();
        ctx.setUseConversationEntityManager(false);
        ctx.setViewUri(selectUri);
        return ctx;
    }
}