/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.Product;
import com.dddzer.repository.ProductRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.ProductJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class ProductLazyDataModel extends GenericLazyDataModel<Product, Integer, ProductSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private ProductRepository productRepository;
    @Inject
    transient private ProductJsfConverter productConverter;
    @Inject
    transient private ProductSearchForm productSearchForm;

    private Product[] selectedRows;

    @Override
    protected Repository<Product, Integer> getRepository() {
        return productRepository;
    }

    @Override
    protected Converter getConverter() {
        return productConverter;
    }

    @Override
    protected GenericSearchForm<Product, ProductSearchForm> getSearchForm() {
        return productSearchForm;
    }

    @Override
    protected ConversationContext<Product> getSelectedContext(Product selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return ProductController.newEditContext(selected.getId());
        } else {
            return ProductController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(Product[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public Product[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<Product>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}