/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.dddzer.web.domain;

import java.util.List;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.servlet.http.HttpServletRequest;
import com.dddzer.dao.support.SearchParameters;
import com.dddzer.domain.User;
import com.dddzer.repository.UserRepository;
import com.dddzer.web.conversation.Conversation;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.conversation.ConversationFactory;

/**
 * Stateless controller for User conversation start. Provides also auto-complete support. 
 */
@Named
@Singleton
public class UserController implements ConversationFactory {
    public final static String editUri = "/domain/userEdit.faces";
    public final static String selectUri = "/domain/userSelect.faces";
    private UserRepository userRepository;

    @Inject
    public void setUserRepository(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    // --------------------------------
    // ConversationFactoryImpl
    // --------------------------------

    @Override
    public boolean canCreateConversation(HttpServletRequest request) {
        return selectUri.equals(request.getServletPath());
    }

    @Override
    public Conversation createConversation(HttpServletRequest request) {
        String uri = request.getServletPath();
        if (selectUri.equals(uri)) {
            Conversation conversation = Conversation.newInstance(request);
            ConversationContext<User> ctx = newSearchContext();
            ctx.setLabelWithKey("user");
            conversation.setNextContext(ctx);
            return conversation;
        }

        throw new IllegalStateException("Unexpected conversation creation demand");
    }

    // --------------------------------
    // Autocomplete support
    // --------------------------------

    /**
     * This method is used from primefaces autocomplete components.
     */
    public List<User> complete(String value) {
        SearchParameters sp = new SearchParameters().anywhere().searchPattern(value);
        return userRepository.find(sp);
    }

    // --------------------------------
    // Helper 
    // --------------------------------    

    /**
     * Helper to construct a new ConversationContext to edit an User.
     * @param user the entity to edit.
     */
    public static ConversationContext<User> newEditContext(final User user) {
        ConversationContext<User> ctx = new ConversationContext<User>();
        ctx.setEntity(user); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:account");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext to edit an User.
     * @param id the id of the entity to edit.
     */
    public static ConversationContext<User> newEditContext(final Integer id) {
        ConversationContext<User> ctx = new ConversationContext<User>();
        ctx.setEntityId(id); // used by GenericEditForm.init()
        ctx.setViewUri(editUri);
        ctx.addSourceIgnoringUseConversationEntityManager("form:account");
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext for search/selection.
     */
    public static ConversationContext<User> newSearchContext() {
        ConversationContext<User> ctx = new ConversationContext<User>();
        ctx.setUseConversationEntityManager(false);
        ctx.setViewUri(selectUri);
        return ctx;
    }
}