/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.dddzer.web.domain;

import static com.dddzer.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.dddzer.domain.User;
import com.dddzer.repository.UserRepository;
import com.dddzer.repository.support.Repository;
import com.dddzer.web.conversation.ConversationContext;
import com.dddzer.web.converter.UserJsfConverter;
import com.dddzer.web.domain.support.GenericLazyDataModel;
import com.dddzer.web.domain.support.GenericSearchForm;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class UserLazyDataModel extends GenericLazyDataModel<User, Integer, UserSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private UserRepository userRepository;
    @Inject
    transient private UserJsfConverter userConverter;
    @Inject
    transient private UserSearchForm userSearchForm;

    private User[] selectedRows;

    @Override
    protected Repository<User, Integer> getRepository() {
        return userRepository;
    }

    @Override
    protected Converter getConverter() {
        return userConverter;
    }

    @Override
    protected GenericSearchForm<User, UserSearchForm> getSearchForm() {
        return userSearchForm;
    }

    @Override
    protected ConversationContext<User> getSelectedContext(User selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return UserController.newEditContext(selected.getId());
        } else {
            return UserController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(User[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public User[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<User>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}