/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.dddzer.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.dddzer.domain.Part;
import com.dddzer.repository.PartGenerator;
import com.dddzer.dao.PartDao;

/**
 * Integration test on PartDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class PartDaoImplTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(PartDaoImplTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private PartDao partDao;

    @Inject
    private PartGenerator partGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Part part = partGenerator.getPart();

        // add it to a Set before saving (force equals/hashcode)
        Set<Part> set = newHashSet(part, part);
        assertThat(set).hasSize(1);

        partDao.save(part);
        entityManager.flush();

        // reload it from cache and check equality
        Part model = new Part();
        model.setId(part.getId());
        assertThat(part).isEqualTo(partDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(part).isEqualTo(partDao.get(model));
    }
}