/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.dddzer.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.dddzer.domain.User;
import com.dddzer.repository.UserGenerator;
import com.dddzer.dao.UserDao;

/**
 * Integration test on UserDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UserDaoImplTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UserDaoImplTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private UserDao userDao;

    @Inject
    private UserGenerator userGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        User user = userGenerator.getUser();

        // add it to a Set before saving (force equals/hashcode)
        Set<User> set = newHashSet(user, user);
        assertThat(set).hasSize(1);

        userDao.save(user);
        entityManager.flush();

        // reload it from cache and check equality
        User model = new User();
        model.setId(user.getId());
        assertThat(user).isEqualTo(userDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(user.getId()).isEqualTo(userDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(user).isNotEqualTo(userDao.get(model));
    }
}